const JsonStore = require('../utils/JsonStore');
// Alimentos semilla; se fusionarán en el almacenamiento local si faltan
const seedFoods = [
  // Proteínas
  {
    id: 1,
    nombre: "Pechuga de Pollo (cocida)",
    barcode: "7896235891234",
    categoria: "Proteínas",
    marca: "Genérica",
    cantidad: 100,
    unidad: "g",
    calorias: 165,
    proteina: 31,
    carbohidratos: 0,
    grasas: 3.6,
    activo: true,
  },
  {
    id: 2,
    nombre: "Huevo completo",
    barcode: "7891234567890",
    categoria: "Proteínas",
    marca: "Genérica",
    cantidad: 1,
    unidad: "unidad",
    calorias: 78,
    proteina: 6.6,
    carbohidratos: 0.6,
    grasas: 5.3,
    activo: true,
  },
  {
    id: 3,
    nombre: "Atún en agua (enlatado)",
    barcode: "7896236891234",
    categoria: "Proteínas",
    marca: "Genérica",
    cantidad: 100,
    unidad: "g",
    calorias: 96,
    proteina: 21,
    carbohidratos: 0,
    grasas: 1.3,
    activo: true,
  },
  {
    id: 4,
    nombre: "Salmón (cocido)",
    barcode: "7896237891234",
    categoria: "Proteínas",
    marca: "Genérica",
    cantidad: 100,
    unidad: "g",
    calorias: 206,
    proteina: 22,
    carbohidratos: 0,
    grasas: 12.3,
    activo: true,
  },
  {
    id: 5,
    nombre: "Carne Magra (res)",
    barcode: "7896238891234",
    categoria: "Proteínas",
    marca: "Genérica",
    cantidad: 100,
    unidad: "g",
    calorias: 182,
    proteina: 26,
    carbohidratos: 0,
    grasas: 8.1,
    activo: true,
  },
  // Carbohidratos
  {
    id: 6,
    nombre: "Arroz blanco cocido",
    barcode: "7896239891234",
    categoria: "Carbohidratos",
    marca: "Genérica",
    cantidad: 100,
    unidad: "g",
    calorias: 130,
    proteina: 2.7,
    carbohidratos: 28,
    grasas: 0.3,
    activo: true,
  },
  {
    id: 7,
    nombre: "Pan Integral",
    barcode: "7896240891234",
    categoria: "Carbohidratos",
    marca: "Genérica",
    cantidad: 1,
    unidad: "rebanada",
    calorias: 80,
    proteina: 4,
    carbohidratos: 14,
    grasas: 1,
    activo: true,
  },
  {
    id: 8,
    nombre: "Plátano",
    barcode: "7896241891234",
    categoria: "Carbohidratos",
    marca: "Genérica",
    cantidad: 1,
    unidad: "unidad",
    calorias: 105,
    proteina: 1.3,
    carbohidratos: 27,
    grasas: 0.3,
    activo: true,
  },
  // Grasas
  {
    id: 9,
    nombre: "Aceite de Oliva",
    barcode: "7896242891234",
    categoria: "Grasas",
    marca: "Genérica",
    cantidad: 1,
    unidad: "cucharada",
    calorias: 120,
    proteina: 0,
    carbohidratos: 0,
    grasas: 13.5,
    activo: true,
  },
  {
    id: 10,
    nombre: "Aguacate",
    barcode: "7896243891234",
    categoria: "Grasas",
    marca: "Genérica",
    cantidad: 100,
    unidad: "g",
    calorias: 160,
    proteina: 2,
    carbohidratos: 9,
    grasas: 15,
    activo: true,
  },
  {
    id: 11,
    nombre: "JDQR - Frijoles cocidos, 100 gramos",
    barcode: null,
    categoria: "Carbohidratos",
    marca: "Genérica",
    cantidad: 100,
    unidad: "g",
    calorias: 115,
    proteina: 7,
    carbohidratos: 21,
    grasas: 0,
    activo: true,
  },
  {
    id: 12,
    nombre: "JDQR - Papaya, 100 gramos",
    barcode: null,
    categoria: "Carbohidratos",
    marca: "Genérica",
    cantidad: 100,
    unidad: "g",
    calorias: 50,
    proteina: 0,
    carbohidratos: 13,
    grasas: 0,
    activo: true,
  },
  {
    id: 13,
    nombre: "JDQR - Alberja, 100 gramos",
    barcode: null,
    categoria: "Carbohidratos",
    marca: "Genérica",
    cantidad: 100,
    unidad: "g",
    calorias: 81,
    proteina: 5,
    carbohidratos: 14,
    grasas: 0,
    activo: true,
  },
  {
    id: 14,
    nombre: "JDQR - Durazno, 100 gramos",
    barcode: null,
    categoria: "Carbohidratos",
    marca: "Genérica",
    cantidad: 100,
    unidad: "g",
    calorias: 44,
    proteina: 1,
    carbohidratos: 10,
    grasas: 0,
    activo: true,
  },
  {
    id: 15,
    nombre: "JDQR - Manzana, 100 gramos",
    barcode: null,
    categoria: "Carbohidratos",
    marca: "Genérica",
    cantidad: 100,
    unidad: "g",
    calorias: 52,
    proteina: 0,
    carbohidratos: 14,
    grasas: 0,
    activo: true,
  },
  {
    id: 16,
    nombre: "JDQR - Fresa, 100 gramos",
    barcode: null,
    categoria: "Carbohidratos",
    marca: "Genérica",
    cantidad: 100,
    unidad: "g",
    calorias: 32,
    proteina: 0,
    carbohidratos: 8,
    grasas: 0,
    activo: true,
  },
  {
    id: 17,
    nombre: "JDQR - Azucar, 100 gramos",
    barcode: null,
    categoria: "Carbohidratos",
    marca: "Genérica",
    cantidad: 100,
    unidad: "g",
    calorias: 399,
    proteina: 0,
    carbohidratos: 100,
    grasas: 0,
    activo: true,
  },
  {
    id: 18,
    nombre: "JDQR - Banano, 100 gramos",
    barcode: null,
    categoria: "Carbohidratos",
    marca: "Genérica",
    cantidad: 100,
    unidad: "g",
    calorias: 89,
    proteina: 1,
    carbohidratos: 23,
    grasas: 0,
    activo: true,
  },
  {
    id: 19,
    nombre: "JDQR - Zanahoria, 100 gramos",
    barcode: null,
    categoria: "Carbohidratos",
    marca: "Genérica",
    cantidad: 100,
    unidad: "g",
    calorias: 32,
    proteina: 1,
    carbohidratos: 7,
    grasas: 0,
    activo: true,
  },
  {
    id: 20,
    nombre: "JDQR - Maíz, 100 gramos",
    barcode: null,
    categoria: "Carbohidratos",
    marca: "Genérica",
    cantidad: 100,
    unidad: "g",
    calorias: 365,
    proteina: 9,
    carbohidratos: 74,
    grasas: 5,
    activo: true,
  },
  {
    id: 21,
    nombre: "JDQR - Mango, 100 gramos",
    barcode: null,
    categoria: "Carbohidratos",
    marca: "Genérica",
    cantidad: 100,
    unidad: "g",
    calorias: 60,
    proteina: 0,
    carbohidratos: 15,
    grasas: 0,
    activo: true,
  },
  {
    id: 22,
    nombre: "JDQR - Miel, 100 gramos",
    barcode: null,
    categoria: "Carbohidratos",
    marca: "Genérica",
    cantidad: 100,
    unidad: "g",
    calorias: 304,
    proteina: 1,
    carbohidratos: 82,
    grasas: 0,
    activo: true,
  },
  {
    id: 23,
    nombre: "JDQR - Kiwi, 100 gramos",
    barcode: null,
    categoria: "Carbohidratos",
    marca: "Genérica",
    cantidad: 100,
    unidad: "g",
    calorias: 73,
    proteina: 1,
    carbohidratos: 15,
    grasas: 1,
    activo: true,
  },
  {
    id: 24,
    nombre: "JDQR - Melón, 100 gramos",
    barcode: null,
    categoria: "Carbohidratos",
    marca: "Genérica",
    cantidad: 100,
    unidad: "g",
    calorias: 35,
    proteina: 1,
    carbohidratos: 8,
    grasas: 0,
    activo: true,
  },
  {
    id: 25,
    nombre: "JDQR - Arepa, 100 gramos",
    barcode: null,
    categoria: "Carbohidratos",
    marca: "Genérica",
    cantidad: 100,
    unidad: "g",
    calorias: 190,
    proteina: 5,
    carbohidratos: 31,
    grasas: 5,
    activo: true,
  },
  {
    id: 26,
    nombre: "JDQR - Crispetas, 100 gramos",
    barcode: null,
    categoria: "Carbohidratos",
    marca: "Genérica",
    cantidad: 100,
    unidad: "g",
    calorias: 375,
    proteina: 11,
    carbohidratos: 74,
    grasas: 4,
    activo: true,
  },
  {
    id: 27,
    nombre: "JDQR - Maní, 100 gramos",
    barcode: null,
    categoria: "Grasas",
    marca: "Genérica",
    cantidad: 100,
    unidad: "g",
    calorias: 567,
    proteina: 26,
    carbohidratos: 16,
    grasas: 49,
    activo: true,
  },
  {
    id: 28,
    nombre: "JDQR - Granola, 100 gramos",
    barcode: null,
    categoria: "Carbohidratos",
    marca: "Genérica",
    cantidad: 100,
    unidad: "g",
    calorias: 470,
    proteina: 10,
    carbohidratos: 81,
    grasas: 10,
    activo: true,
  },
  {
    id: 29,
    nombre: "JDQR - Plátano maduro/verde, 100 gramos",
    barcode: null,
    categoria: "Carbohidratos",
    marca: "Genérica",
    cantidad: 100,
    unidad: "g",
    calorias: 130,
    proteina: 1,
    carbohidratos: 32,
    grasas: 0,
    activo: true,
  },
  {
    id: 30,
    nombre: "JDQR - Natilla (porción pequeña), 1 porción",
    barcode: null,
    categoria: "Carbohidratos",
    marca: "Genérica",
    cantidad: 1,
    unidad: "porción",
    calorias: 146,
    proteina: 4,
    carbohidratos: 33,
    grasas: 0,
    activo: true,
  },
  {
    id: 31,
    nombre: "JDQR - Chatas de res, 100 gramos",
    barcode: null,
    categoria: "Proteínas",
    marca: "Genérica",
    cantidad: 100,
    unidad: "g",
    calorias: 200,
    proteina: 22,
    carbohidratos: 0,
    grasas: 12,
    activo: true,
  },
  {
    id: 32,
    nombre: "JDQR - Zumo de naranja, 100 gramos",
    barcode: null,
    categoria: "Carbohidratos",
    marca: "Genérica",
    cantidad: 100,
    unidad: "g",
    calorias: 45,
    proteina: 1,
    carbohidratos: 10,
    grasas: 0,
    activo: true,
  },
  {
    id: 33,
    nombre: "JDQR - Pan blanco/integral, 100 gramos",
    barcode: null,
    categoria: "Carbohidratos",
    marca: "Genérica",
    cantidad: 100,
    unidad: "g",
    calorias: 265,
    proteina: 9,
    carbohidratos: 50,
    grasas: 3,
    activo: true,
  },
  {
    id: 34,
    nombre: "JDQR - Buñuelo mediano, 1 unidad",
    barcode: null,
    categoria: "Carbohidratos",
    marca: "Genérica",
    cantidad: 1,
    unidad: "unidad",
    calorias: 248,
    proteina: 4,
    carbohidratos: 31,
    grasas: 12,
    activo: true,
  },
  {
    id: 35,
    nombre: "JDQR - Leche entera, 240 mililitros",
    barcode: null,
    categoria: "Proteínas",
    marca: "Genérica",
    cantidad: 240,
    unidad: "ml",
    calorias: 110,
    proteina: 7,
    carbohidratos: 11,
    grasas: 7,
    activo: true,
  },
  {
    id: 36,
    nombre: "JDQR - Huevo entero, 1 unidad",
    barcode: null,
    categoria: "Proteínas",
    marca: "Genérica",
    cantidad: 1,
    unidad: "unidad",
    calorias: 78,
    proteina: 6,
    carbohidratos: 1,
    grasas: 5,
    activo: true,
  },
  {
    id: 37,
    nombre: "JDQR - Robalo crudo, 100 gramos",
    barcode: null,
    categoria: "Proteínas",
    marca: "Genérica",
    cantidad: 100,
    unidad: "g",
    calorias: 124,
    proteina: 24,
    carbohidratos: 0,
    grasas: 3,
    activo: true,
  },
  {
    id: 38,
    nombre: "JDQR - Arroz cocido, 100 gramos",
    barcode: null,
    categoria: "Carbohidratos",
    marca: "Genérica",
    cantidad: 100,
    unidad: "g",
    calorias: 125,
    proteina: 3,
    carbohidratos: 28,
    grasas: 0,
    activo: true,
  },
  {
    id: 39,
    nombre: "JDQR - Papas fritas, 100 gramos",
    barcode: null,
    categoria: "Carbohidratos",
    marca: "Genérica",
    cantidad: 100,
    unidad: "g",
    calorias: 307,
    proteina: 3,
    carbohidratos: 40,
    grasas: 15,
    activo: true,
  },
  {
    id: 40,
    nombre: "JDQR - Lentejas cocinadas, 100 gramos",
    barcode: null,
    categoria: "Carbohidratos",
    marca: "Genérica",
    cantidad: 100,
    unidad: "g",
    calorias: 115,
    proteina: 9,
    carbohidratos: 20,
    grasas: 0,
    activo: true,
  },
  {
    id: 41,
    nombre: "JDQR - Papa cocinada, 100 gramos",
    barcode: null,
    categoria: "Carbohidratos",
    marca: "Genérica",
    cantidad: 100,
    unidad: "g",
    calorias: 92,
    proteina: 2,
    carbohidratos: 21,
    grasas: 0,
    activo: true,
  },
  {
    id: 42,
    nombre: "JDQR - Garbanzo cocido, 100 gramos",
    barcode: null,
    categoria: "Carbohidratos",
    marca: "Genérica",
    cantidad: 100,
    unidad: "g",
    calorias: 164,
    proteina: 9,
    carbohidratos: 27,
    grasas: 3,
    activo: true,
  },
  {
    id: 43,
    nombre: "JDQR - Sushi - General, 26 gramos",
    barcode: null,
    categoria: "Carbohidratos",
    marca: "Genérica",
    cantidad: 26,
    unidad: "g",
    calorias: 37,
    proteina: 1,
    carbohidratos: 8,
    grasas: 0,
    activo: true,
  },
  {
    id: 44,
    nombre: "JDQR - Pollo con piel (menos pechuga), 100 gramos",
    barcode: null,
    categoria: "Proteínas",
    marca: "Genérica",
    cantidad: 100,
    unidad: "g",
    calorias: 239,
    proteina: 27,
    carbohidratos: 0,
    grasas: 14,
    activo: true,
  },
  {
    id: 45,
    nombre: "JDQR - Carne de cerdo magra asada, 100 gramos",
    barcode: null,
    categoria: "Proteínas",
    marca: "Genérica",
    cantidad: 100,
    unidad: "g",
    calorias: 170,
    proteina: 26,
    carbohidratos: 0,
    grasas: 6,
    activo: true,
  },
  {
    id: 46,
    nombre: "JDQR - Carne de cerdo (lomo, pierna), 100 gramos",
    barcode: null,
    categoria: "Proteínas",
    marca: "Genérica",
    cantidad: 100,
    unidad: "g",
    calorias: 242,
    proteina: 27,
    carbohidratos: 0,
    grasas: 14,
    activo: true,
  },
  {
    id: 47,
    nombre: "JDQR - Carne (cruda) con poca grasa, 100 gramos",
    barcode: null,
    categoria: "Proteínas",
    marca: "Genérica",
    cantidad: 100,
    unidad: "g",
    calorias: 185,
    proteina: 26,
    carbohidratos: 0,
    grasas: 9,
    activo: true,
  },
  {
    id: 48,
    nombre: "JDQR - Bola de pierna de res, 100 gramos",
    barcode: null,
    categoria: "Proteínas",
    marca: "Genérica",
    cantidad: 100,
    unidad: "g",
    calorias: 130,
    proteina: 22,
    carbohidratos: 0,
    grasas: 4,
    activo: true,
  },
  {
    id: 49,
    nombre: "JDQR - Pastas cocidas (poca agua), 590 gramos",
    barcode: null,
    categoria: "Carbohidratos",
    marca: "Genérica",
    cantidad: 590,
    unidad: "g",
    calorias: 540,
    proteina: 20,
    carbohidratos: 122,
    grasas: 0,
    activo: true,
  },
  {
    id: 50,
    nombre: "JDQR - Mezcla frutos secos, 30 gramos",
    barcode: null,
    categoria: "Grasas",
    marca: "Genérica",
    cantidad: 30,
    unidad: "g",
    calorias: 177,
    proteina: 7,
    carbohidratos: 5,
    grasas: 14,
    activo: true,
  },
  {
    id: 51,
    nombre: "JDQR - Arvejas cocinadas, 100 gramos",
    barcode: null,
    categoria: "Carbohidratos",
    marca: "Genérica",
    cantidad: 100,
    unidad: "g",
    calorias: 123,
    proteina: 7,
    carbohidratos: 23,
    grasas: 0,
    activo: true,
  },
  {
    id: 52,
    nombre: "JDQR - Mantequilla de maní, 17 gramos",
    barcode: null,
    categoria: "Grasas",
    marca: "Genérica",
    cantidad: 17,
    unidad: "g",
    calorias: 100,
    proteina: 4,
    carbohidratos: 3,
    grasas: 8,
    activo: true,
  },
  {
    id: 53,
    nombre: "JDQR - Claras de huevo, 100 gramos",
    barcode: null,
    categoria: "Proteínas",
    marca: "Genérica",
    cantidad: 100,
    unidad: "g",
    calorias: 52,
    proteina: 11,
    carbohidratos: 7,
    grasas: 2,
    activo: true,
  },
  {
    id: 54,
    nombre: "JDQR - Pizza (tamaño promedio), 1 unidad",
    barcode: null,
    categoria: "Carbohidratos",
    marca: "Genérica",
    cantidad: 1,
    unidad: "unidad",
    calorias: 300,
    proteina: 10,
    carbohidratos: 31,
    grasas: 15,
    activo: true,
  },
  {
    id: 55,
    nombre: "JDQR - Sushi - Philadelphia Roll, 26 gramos",
    barcode: null,
    categoria: "Carbohidratos",
    marca: "Genérica",
    cantidad: 26,
    unidad: "g",
    calorias: 41,
    proteina: 1,
    carbohidratos: 6,
    grasas: 1,
    activo: true,
  },
  {
    id: 56,
    nombre: "JDQR - Sushi - California Roll, 26 gramos",
    barcode: null,
    categoria: "Carbohidratos",
    marca: "Genérica",
    cantidad: 26,
    unidad: "g",
    calorias: 33,
    proteina: 1,
    carbohidratos: 6,
    grasas: 0,
    activo: true,
  },
  {
    id: 57,
    nombre: "JDQR - Avena en hojuelas, 100 gramos",
    barcode: null,
    categoria: "Carbohidratos",
    marca: "Genérica",
    cantidad: 100,
    unidad: "g",
    calorias: 367,
    proteina: 10,
    carbohidratos: 70,
    grasas: 7,
    activo: true,
  },
];

// Persistencia en JSON local
const foodStore = new JsonStore('foods.json', seedFoods);
let foodDatabase = foodStore.getAll();
// Fusionar semillas ausentes (por nombre+categoría o barcode)
const normKey = (it) => (it.barcode ? `b:${it.barcode}` : `n:${(it.nombre || '').toLowerCase()}|${(it.categoria || '').toLowerCase()}`);
const map = new Map(foodDatabase.map(f => [normKey(f), f]));
seedFoods.forEach(f => {
  const k = normKey(f);
  if (!map.has(k)) {
    // sin id fijo para evitar colisiones; se asigna más adelante
    map.set(k, { ...f, id: undefined });
  }
});
foodDatabase = Array.from(map.values()).map((f, idx) => ({
  ...f,
  id: f.id ?? (idx + 1),
}));
// Guardar si se añadieron nuevas semillas
foodStore.setAll(foodDatabase);
let nextFoodId = foodDatabase.length > 0 ? Math.max(...foodDatabase.map(f => f.id)) + 1 : 1;

const FoodDatabase = {
  // Obtener todos los alimentos
  getAll: () => foodDatabase.filter((f) => f.activo),

  // Buscar por código de barras
  findByBarcode: (barcode) => {
    const food = foodDatabase.find((f) => f.barcode === barcode && f.activo);
    return food || null;
  },

  // Buscar por nombre o marca
  search: (query) => {
    const q = query.toLowerCase();
    return foodDatabase.filter(
      (f) =>
        f.activo &&
        (f.nombre.toLowerCase().includes(q) ||
          f.marca.toLowerCase().includes(q))
    );
  },

  // Crear nuevo alimento
  create: (foodData) => {
    const newFood = {
      id: nextFoodId++,
      ...foodData,
      activo: true,
      createdAt: new Date(),
    };
    foodDatabase.push(newFood);
    foodStore.setAll(foodDatabase);
    return newFood;
  },

  // Actualizar alimento
  update: (id, updates) => {
    const index = foodDatabase.findIndex((f) => f.id === id);
    if (index !== -1) {
      foodDatabase[index] = { ...foodDatabase[index], ...updates };
      foodStore.setAll(foodDatabase);
      return foodDatabase[index];
    }
    return null;
  },

  // Eliminar (soft delete)
  delete: (id) => {
    const index = foodDatabase.findIndex((f) => f.id === id);
    if (index !== -1) {
      foodDatabase[index].activo = false;
      foodStore.setAll(foodDatabase);
      return true;
    }
    return false;
  },

  // Obtener por ID
  getById: (id) => foodDatabase.find((f) => f.id === id && f.activo),

  // Obtener por categoría
  getByCategory: (category) =>
    foodDatabase.filter((f) => f.categoria === category && f.activo),

  // Obtener todas las categorías únicas
  getCategories: () => [
    ...new Set(foodDatabase.filter((f) => f.activo).map((f) => f.categoria)),
  ],

  // Crear respaldo manual del archivo de alimentos
  backup: () => {
    const resultPath = foodStore.backup('foods');
    return resultPath;
  },
};

module.exports = FoodDatabase;
