// Banco de alimentos pre-poblado con información nutricional
const foodItems = [
  // Proteínas
  {
    id: 1,
    nombre: "Pechuga de Pollo (cocida)",
    categoria: "Proteínas",
    cantidad: 100,
    unidad: "g",
    calorias: 165,
    proteina: 31,
    carbohidratos: 0,
    grasas: 3.6,
  },
  {
    id: 2,
    nombre: "Huevo completo",
    categoria: "Proteínas",
    cantidad: 1,
    unidad: "unidad",
    calorias: 78,
    proteina: 6.6,
    carbohidratos: 0.6,
    grasas: 5.3,
  },
  {
    id: 3,
    nombre: "Atún en agua (enlatado)",
    categoria: "Proteínas",
    cantidad: 100,
    unidad: "g",
    calorias: 96,
    proteina: 21,
    carbohidratos: 0,
    grasas: 1.3,
  },
  {
    id: 4,
    nombre: "Salmón (cocido)",
    categoria: "Proteínas",
    cantidad: 100,
    unidad: "g",
    calorias: 206,
    proteina: 22,
    carbohidratos: 0,
    grasas: 12.3,
  },
  {
    id: 5,
    nombre: "Carne Magra (res)",
    categoria: "Proteínas",
    cantidad: 100,
    unidad: "g",
    calorias: 182,
    proteina: 26,
    carbohidratos: 0,
    grasas: 8.1,
  },
  {
    id: 6,
    nombre: "Pavo (cocido)",
    categoria: "Proteínas",
    cantidad: 100,
    unidad: "g",
    calorias: 135,
    proteina: 29,
    carbohidratos: 0,
    grasas: 0.7,
  },
  // Carbohidratos
  {
    id: 7,
    nombre: "Arroz blanco cocido",
    categoria: "Carbohidratos",
    cantidad: 100,
    unidad: "g",
    calorias: 130,
    proteina: 2.7,
    carbohidratos: 28,
    grasas: 0.3,
  },
  {
    id: 8,
    nombre: "Pan Integral",
    categoria: "Carbohidratos",
    cantidad: 1,
    unidad: "rebanada",
    calorias: 80,
    proteina: 4,
    carbohidratos: 14,
    grasas: 1,
  },
  {
    id: 9,
    nombre: "Pasta cocida",
    categoria: "Carbohidratos",
    cantidad: 100,
    unidad: "g",
    calorias: 131,
    proteina: 5,
    carbohidratos: 25,
    grasas: 1.1,
  },
  {
    id: 10,
    nombre: "Avena cocida",
    categoria: "Carbohidratos",
    cantidad: 100,
    unidad: "g",
    calorias: 68,
    proteina: 2.4,
    carbohidratos: 12,
    grasas: 1.4,
  },
  {
    id: 11,
    nombre: "Batata cocida",
    categoria: "Carbohidratos",
    cantidad: 100,
    unidad: "g",
    calorias: 86,
    proteina: 1.6,
    carbohidratos: 20,
    grasas: 0.1,
  },
  {
    id: 12,
    nombre: "Plátano",
    categoria: "Carbohidratos",
    cantidad: 1,
    unidad: "unidad",
    calorias: 105,
    proteina: 1.3,
    carbohidratos: 27,
    grasas: 0.3,
  },
  // Grasas
  {
    id: 13,
    nombre: "Aceite de Oliva",
    categoria: "Grasas",
    cantidad: 1,
    unidad: "cucharada",
    calorias: 120,
    proteina: 0,
    carbohidratos: 0,
    grasas: 13.5,
  },
  {
    id: 14,
    nombre: "Aguacate",
    categoria: "Grasas",
    cantidad: 100,
    unidad: "g",
    calorias: 160,
    proteina: 2,
    carbohidratos: 9,
    grasas: 15,
  },
  {
    id: 15,
    nombre: "Nueces",
    categoria: "Grasas",
    cantidad: 28,
    unidad: "g",
    calorias: 196,
    proteina: 4.3,
    carbohidratos: 4.3,
    grasas: 20,
  },
  {
    id: 16,
    nombre: "Almendras",
    categoria: "Grasas",
    cantidad: 28,
    unidad: "g",
    calorias: 164,
    proteina: 6,
    carbohidratos: 6,
    grasas: 14,
  },
  {
    id: 17,
    nombre: "Mantequilla de Maní",
    categoria: "Grasas",
    cantidad: 2,
    unidad: "cucharadas",
    calorias: 188,
    proteina: 8,
    carbohidratos: 7,
    grasas: 16,
  },
  // Verduras y Frutas
  {
    id: 18,
    nombre: "Brócoli (cocido)",
    categoria: "Verduras",
    cantidad: 100,
    unidad: "g",
    calorias: 34,
    proteina: 2.8,
    carbohidratos: 7,
    grasas: 0.4,
  },
  {
    id: 19,
    nombre: "Espinaca (cruda)",
    categoria: "Verduras",
    cantidad: 100,
    unidad: "g",
    calorias: 23,
    proteina: 2.7,
    carbohidratos: 3.6,
    grasas: 0.4,
  },
  {
    id: 20,
    nombre: "Zanahoria (cruda)",
    categoria: "Verduras",
    cantidad: 100,
    unidad: "g",
    calorias: 41,
    proteina: 0.9,
    carbohidratos: 10,
    grasas: 0.2,
  },
  {
    id: 21,
    nombre: "Manzana",
    categoria: "Frutas",
    cantidad: 1,
    unidad: "unidad",
    calorias: 95,
    proteina: 0.5,
    carbohidratos: 25,
    grasas: 0.3,
  },
  {
    id: 22,
    nombre: "Naranja",
    categoria: "Frutas",
    cantidad: 1,
    unidad: "unidad",
    calorias: 62,
    proteina: 1.2,
    carbohidratos: 15.4,
    grasas: 0.3,
  },
  {
    id: 23,
    nombre: "Fresas",
    categoria: "Frutas",
    cantidad: 100,
    unidad: "g",
    calorias: 32,
    proteina: 0.8,
    carbohidratos: 7.7,
    grasas: 0.3,
  },
  // Lácteos
  {
    id: 24,
    nombre: "Yogurt Griego (bajo en grasa)",
    categoria: "Lácteos",
    cantidad: 100,
    unidad: "g",
    calorias: 59,
    proteina: 10,
    carbohidratos: 3.3,
    grasas: 0.4,
  },
  {
    id: 25,
    nombre: "Queso Fresco",
    categoria: "Lácteos",
    cantidad: 30,
    unidad: "g",
    calorias: 107,
    proteina: 11,
    carbohidratos: 1.3,
    grasas: 6.5,
  },
  {
    id: 26,
    nombre: "Leche descremada",
    categoria: "Lácteos",
    cantidad: 240,
    unidad: "ml",
    calorias: 86,
    proteina: 8.4,
    carbohidratos: 12,
    grasas: 0.2,
  },
];

module.exports = foodItems;
